function Morvolc_SaveXLS(xlsFolFil,morRes)
% Name: Morvolc_SaveXLS
% Author: Daniel O'Hara
% Date: 03/17/2021 (mm/dd/yyyy)
% Description: Script to convert the MorVolc result structure into an Excel
%   file.
%
% Input:
%   xlsFolFil: Excel file name and folder.
%   morRes: MorVolc result structure.

%% General Parameters
gp = {'Tif File:',morRes.GeneralParams.inputs.tifFile;...
    'Resolution:',morRes.GeneralParams.inputs.dx;...
    'Contour Iteration:',morRes.GeneralParams.inputs.contIter;...
    'Craters:',~isempty(morRes.GeneralParams.inputs.craterXY);...
    'Natural Interpolation:',morRes.GeneralParams.inputs.interpSurfaces.Natural==1;...
    'IDW Interpolation:',morRes.GeneralParams.inputs.interpSurfaces.IDW==1;...
    'Kriging Interpolation:',morRes.GeneralParams.inputs.interpSurfaces.Kriging==1};

xlswrite(xlsFolFil,gp,'General_Parameters')
    
%% Size Parameters
szp = {'Basal Area (m2):',morRes.SizeParams.Basal_Area;...
    'Basal Width (m):',morRes.SizeParams.Basal_Width;...
    'Basal Ellipse Major Axis (m):',morRes.SizeParams.Major_Basal_Axis;...
    'Basal Ellipse Minor Axis (m):',morRes.SizeParams.Minor_Basal_Axis;...
    'Basal Ellipse X Centroid (m):',morRes.SizeParams.Basal_Ellipse.x0;...
    'Basal Ellipse Y Centroid (m):',morRes.SizeParams.Basal_Ellipse.y0;...
    'Basal Ellipse Axis Ellipticity:',morRes.SizeParams.Basal_Axis_Ellipticity;...
    [],[];...
    'Summit Area (m2):',morRes.SizeParams.Summit_Area;...
    'Summit Width (m):',morRes.SizeParams.Summit_Width;...
    'Summit Ellipse Major Axis (m):',morRes.SizeParams.Summit_Basal_Axis;...
    'Summit Ellipse X Centroid (m):',morRes.SizeParams.Summit_Ellipse.x0;...
    'Summit Ellipse Y Centroid (m):',morRes.SizeParams.Summit_Ellipse.y0;...
    'Summit Ellipse Ellipticity:',morRes.SizeParams.Summit_Basal_Axis_Ellipticity;...
    [],[];...
    'Maximum Height (m):',morRes.SizeParams.Maximum_Height;...
    'Maximum Volume (m3):',morRes.SizeParams.Maximum_Volume;...
    'Minimum Eroded Volume (m3):',morRes.SizeParams.Minimum_Eroded_Volume;...
    [],[];...
    'Peak Heights (m):',[]};
hStart = size(szp,1)+1;
szp = [szp;{[],'Natural:';...
    [],'IDW:';...
    [],'Kriging:';...
    [],[];...
    'Volumes (m3):',[]}];
vStart = size(szp,1)+1;
szp = [szp;{[],'Natural:';...
    [],'IDW:';...
    [],'Kriging:';...
    [],[];...
    'Max Anywhere Height',[];...
    [],[]}];
haStart = size(szp,1)+1;
szp = [szp;{[],'Natural:';...
    [],'IDW:';...
    [],'Kriging:'}];

szp{haStart-1,3} = 'Height (m)';
szp{haStart-1,4} = 'X (m)';
szp{haStart-1,5} = 'Y (m)';

if morRes.GeneralParams.inputs.interpSurfaces.Natural
    szp{hStart,3} = morRes.SizeParams.Peak_Height.Natural;
    szp{vStart,3} = morRes.SizeParams.Volume.Natural;
    szp{haStart,3} = morRes.SizeParams.Any_Height.Natural.Height;
    szp{haStart,4} = morRes.SizeParams.Any_Height.Natural.X;
    szp{haStart,5} = morRes.SizeParams.Any_Height.Natural.Y;
end

if morRes.GeneralParams.inputs.interpSurfaces.IDW
    szp{hStart+1,3} = morRes.SizeParams.Peak_Height.IDW;
    szp{vStart+1,3} = morRes.SizeParams.Volume.IDW;
    szp{haStart+1,3} = morRes.SizeParams.Any_Height.IDW.Height;
    szp{haStart+1,4} = morRes.SizeParams.Any_Height.IDW.X;
    szp{haStart+1,5} = morRes.SizeParams.Any_Height.IDW.Y;
end

if morRes.GeneralParams.inputs.interpSurfaces.Kriging
    szp{hStart+2,3} = morRes.SizeParams.Peak_Height.Kriging;
    szp{vStart+2,3} = morRes.SizeParams.Volume.Kriging;
    szp{haStart+2,3} = morRes.SizeParams.Any_Height.Kriging.Height;
    szp{haStart+2,4} = morRes.SizeParams.Any_Height.Kriging.X;
    szp{haStart+2,5} = morRes.SizeParams.Any_Height.Kriging.Y;
end

xlswrite(xlsFolFil,szp,'Size_Parameters')

%% Orientation Parameters
op = {'Basal Ellipse Orientation (deg.):',morRes.OrientParams.Basal_Major_Axis_Azimuth;...
    'Summit Ellipse Orientation (deg.):',morRes.OrientParams.Summit_Major_Axis_Azimuth;...
    [],[];...
    'CONTOUR (m)','ELLIPSE ORIENTATION (deg.)'};
xlsI = size(op,1)+1;
for i = 1:length(morRes.OrientParams.Contour_Values)
    op{xlsI,1} = morRes.OrientParams.Contour_Values(i);
    op{xlsI,2} = morRes.OrientParams.Contour_Major_Axis_Azimuths(i);
    xlsI = xlsI+1;
end

xlswrite(xlsFolFil,op,'Orientation_Parameters')

%% Shape Parameters
shp = {'Mean Contour Maximum Diameter Ellipticity Index:',morRes.ShapeParams.Mean_MaxDiam_Ellipticity_Index;...
    'Mean Contour Best-Fitting Ellipse Ellipticity Index:',morRes.ShapeParams.Mean_BFEllipse_Ellipticity_Index;...
    'Mean Contour Maximum Diameter Irregularity Index:',morRes.ShapeParams.Mean_MaxDiam_Irregularity_Index;...
    'Mean Contour Best-Fitting Ellipse Irregularity Index:',morRes.ShapeParams.Mean_BFEllipse_Irregularity_Index;...
    'Mean Contour Best-Fitting Ellipse Axis Ellipticity:',morRes.ShapeParams.Mean_Ellipse_Ellipticity;...
    [],[];...
    'Summit Width - Basal Width Ratio:',morRes.ShapeParams.SummitWidth_BasalWidth;...
    'Height - Basal Width Ratio:',[]};
hbwI = size(shp,1)+1;
shp = [shp;{[],'Natural:';...
    [],'IDW:';...
    [],'Kriging:';...
    [],[];...
    'Skewness:',[]}];
skI = size(shp,1)+1;
shp = [shp;{[],'X:';...
    [],'Y:';...
    'Kurtosis:',[]}];
kuI = size(shp,1)+1;
shp = [shp;{[],'X:';...
    [],'Y:';...
    [],[]}];

if morRes.GeneralParams.inputs.interpSurfaces.Natural
    shp{hbwI,3} = morRes.ShapeParams.Height_BasalWidth.Natural;
end

if morRes.GeneralParams.inputs.interpSurfaces.IDW
    shp{hbwI+1,3} = morRes.ShapeParams.Height_BasalWidth.IDW;
end

if morRes.GeneralParams.inputs.interpSurfaces.Kriging
    shp{hbwI+2,3} = morRes.ShapeParams.Height_BasalWidth.Kriging;
end

shp{skI,3} = morRes.ShapeParams.Skewness(1);
shp{skI+1,3} = morRes.ShapeParams.Skewness(2);
shp{kuI,3} = morRes.ShapeParams.Kurtosis(1);
shp{kuI+1,3} = morRes.ShapeParams.Kurtosis(2);

shp = [shp;{[],[],[];...
    'CONTOUR (m)','MAX DIAMETER ELLIPTICITY INDEX','BEST-FITTING ELLIPSE ELLIPTICITY INDEX'}];
xlsI = size(shp,1);
shp{xlsI,4} = 'MAX DIAMETER IRREGULARITY INDEX';
shp{xlsI,5} = 'BEST-FITTING ELLIPSE IRREGULARITY INDEX';
shp{xlsI,6} = 'AXIS ELLIPTICITY';
xlsI  = xlsI+1;
for i = 1:length(morRes.ShapeParams.Contour_Values)
    shp{xlsI,1} = morRes.ShapeParams.Contour_Values(i);
    shp{xlsI,2} = morRes.ShapeParams.Contour_MaxDiam_Ellipticity_Indexes(i);
    shp{xlsI,3} = morRes.ShapeParams.Contour_BFEllipse_Ellipticity_Indexes(i);
    shp{xlsI,4} = morRes.ShapeParams.Contour_MaxDiam_Irregularity_Indexes(i);
    shp{xlsI,5} = morRes.ShapeParams.Contour_BFEllipse_Irregularity_Indexes(i);
    shp{xlsI,6} = morRes.ShapeParams.Contour_Axis_Ellipticity(i);
    xlsI = xlsI+1;
end

xlswrite(xlsFolFil,shp,'Shape_Parameters')

%% Slope Parameters
slp = {'Lower Flank Mean Slope (deg.):',morRes.SlopeParams.Lower_Flank_Mean_Slope;...
    'Lower Flank Median Slope (deg.):',morRes.SlopeParams.Lower_Flank_Median_Slope;...
    [],[];...
    'Flank Mean Slope (deg.):',morRes.SlopeParams.Flank_Mean_Slope;...
    'Flank Median Slope (deg.):',morRes.SlopeParams.Flank_Median_Slope;...
    [],[];...
    'Summit Mean Slope (deg.):',morRes.SlopeParams.Summit_Mean_Slope;...
    'Summit Median Slope (deg.):',morRes.SlopeParams.Summit_Median_Slope;...
    [],[];...
    'Whole Edifice Mean Slope (deg.):',morRes.SlopeParams.WholeEdifice_Mean_Slope;...
    'Whole Edifice Median Slope (deg.):',morRes.SlopeParams.WholeEdifice_Median_Slope;...
    [],[];...
    'Contour Maximum Slope (deg.):',morRes.SlopeParams.Max_Slope;...
    'Max Slope Height (m):',morRes.SlopeParams.Max_Slope_Height;...
    'Max Slope Height Fraction:',morRes.SlopeParams.Max_Slope_Height_Fraction;...
    [],[];...
    'CONTOUR (m)','MIN. SLOPE (deg.)'};

slpI = size(slp,1);
slp{slpI,3} = 'MAX. SLOPE (deg.)';
slp{slpI,4} = 'MEAN SLOPE (deg.)';
slp{slpI,5} = 'MEDIAN SLOPE (deg.)';
slpI = slpI + 1;
for i = 1:length(morRes.SlopeParams.Contour_Values)
    slp{slpI,1} = morRes.SlopeParams.Contour_Values(i);
    slp{slpI,2} = morRes.SlopeParams.Contour_Min_Slopes(i);
    slp{slpI,3} = morRes.SlopeParams.Contour_Max_Slopes(i);
    slp{slpI,4} = morRes.SlopeParams.Contour_Mean_Slopes(i);
    slp{slpI,5} = morRes.SlopeParams.Contour_Median_Slopes(i);
    slpI = slpI+1;
end

xlswrite(xlsFolFil,slp,'Slope_Parameters')

%% Peak Parameters
pp = {'Summit Contour Peak Count:',morRes.PeakParams.Summit_Contour_Peak_Count;...
    'Main Flank Contour Peak Count:',morRes.PeakParams.Main_Flank_Contour_Peak_Count;...
    'Lower Flank Contour Peak Count:',morRes.PeakParams.Lower_Flank_Contour_Peak_Count;...
    [],[];...
    'Summit Local Maxima Peak Count:',morRes.PeakParams.Summit_Local_Peak_Count;...
    'Main Flank Local Maxima Peak Count:',morRes.PeakParams.Main_Flank_Local_Peak_Count;...
    'Lower Flank Local Maxima Peak Count:',morRes.PeakParams.Lower_Flank_Local_Peak_Count};
xlswrite(xlsFolFil,pp,'Peak_Parameters')

%% Crater Parameters
if ~isempty(morRes.CraterParams)
    for i = 1:length(morRes.CraterParams.Crater_Area)
        cp = {};
        cp = {'Crater Area (m2):',morRes.CraterParams.Crater_Area(i);...
            'Crater Width (m):',morRes.CraterParams.Crater_Width(i);...
            'Crater Ellipse Major Axis (m):',morRes.CraterParams.Crater_Major_Axis(i);...
            'Crater Ellipse Minor Axis (m):',morRes.CraterParams.Crater_Minor_Axis(i);...
            'Crater Ellipse Azimuth (deg.):',morRes.CraterParams.Crater_Major_Axis_Azimuth(i);...
            [],[];...
            'Crater Maximum Diameter Ellipticity Index:',morRes.CraterParams.Crater_MaxDiam_Ellipticity_Index(i);...
            'Crater Best-Fitting Ellipse Ellipticity Index:',morRes.CraterParams.Crater_BFEllipse_Ellipticity_Index(i);...
            'Crater Maximum Diameter Irregularity Index:',morRes.CraterParams.Crater_MaxDiam_Irregularity_Index(i);...
            'Crater Best-Fitting Ellipse Irregularity Index:',morRes.CraterParams.Crater_BFEllipse_Irregularity_Index(i);...
            'Crater Best-Fitting Ellipse Axis Ellipticity:',morRes.CraterParams.Crater_Axis_Ellipticity(i);...
            [],[];...
            'Crater Maximum Volume (m3):',morRes.CraterParams.Crater_Maximum_Volume(i);...
            'Crater Maximum Depth (m):',morRes.CraterParams.Crater_Maximum_Depth(i);...
            'Crater Depths (m):',[];...
            [],'Natural:'};
        cdI = size(cp,1);
        cp = [cp;{[],'IDW:';...
            [],'Kriging:';...
            [],[];...
            'Crater Volumes (m3):',[];...
            [],'Natural:'}];
        cvI = size(cp,1);
        cp = [cp;{[],'IDW:';...
            [],'Kriging:';...
            [],[];...
            'Crater Width - Basal Width Ratio:',morRes.CraterParams.CraterWidth_BasalWidth(i);...
            'Crater Depth - Crater Width Ratio:',[];...
            [],'Natural:'}];
        cdcwI = size(cp,1);
        cp = [cp;{[],'IDW:';...
            [],'Kriging:';...
            'Crater Depth - Basal Height Ratio:',[];...
            [],'Natural:'}];
        cdbhI = size(cp,1);
        cp = [cp;{[],'IDW:';...
            [],'Kriging:';...
            [],[]}];

        if morRes.GeneralParams.inputs.interpSurfaces.Natural
            cp{cdI,3} = morRes.CraterParams.Crater_Depth{i}.Natural;
            cp{cvI,3} = morRes.CraterParams.Crater_Volume{i}.Natural;
            cp{cdcwI,3} = morRes.CraterParams.CraterDepth_CraterWidth{i}.Natural;
            cp{cdbhI,3} = morRes.CraterParams.CraterDepth_BasalHeight{i}.Natural;
        end

        if morRes.GeneralParams.inputs.interpSurfaces.IDW
            cp{cdI+1,3} = morRes.CraterParams.Crater_Depth{i}.IDW;
            cp{cvI+1,3} = morRes.CraterParams.Crater_Volume{i}.IDW;
            cp{cdcwI+1,3} = morRes.CraterParams.CraterDepth_CraterWidth{i}.IDW;
            cp{cdbhI+1,3} = morRes.CraterParams.CraterDepth_BasalHeight{i}.IDW;
        end

        if morRes.GeneralParams.inputs.interpSurfaces.Kriging
            cp{cdI+2,3} = morRes.CraterParams.Crater_Depth{i}.Kriging;
            cp{cvI+2,3} = morRes.CraterParams.Crater_Volume{i}.Kriging;
            cp{cdcwI+2,3} = morRes.CraterParams.CraterDepth_CraterWidth{i}.Kriging;
            cp{cdbhI+2,3} = morRes.CraterParams.CraterDepth_BasalHeight{i}.Kriging;
        end
        
        cp = [cp;{'Crater Mean Slope (deg.):', morRes.CraterParams.Crater_Mean_Slope(i),[];...
            'Crater Median Slope (deg.):', morRes.CraterParams.Crater_Median_Slope(i),[];...
            [],[],[]}];

        cp = [cp;{'CONTOUR (m)','MIN. SLOPE (deg.)','MAX. SLOPE (deg.)'}];
        cpI = size(cp,1);
        cp{cpI,4} = 'MEAN SLOPE (deg.)';
        cp{cpI,5} = 'MEDIAN SLOPE (deg.)';
        cpI = cpI + 1;
        for j = 1:length(morRes.CraterParams.Crater_Contour_Stats{i}.Crater_Contours)
            cp{cpI,1} = morRes.CraterParams.Crater_Contour_Stats{i}.Crater_Contours(j);
            cp{cpI,2} = morRes.CraterParams.Crater_Contour_Stats{i}.Crater_Min_Slope(j);
            cp{cpI,3} = morRes.CraterParams.Crater_Contour_Stats{i}.Crater_Max_Slope(j);
            cp{cpI,4} = morRes.CraterParams.Crater_Contour_Stats{i}.Crater_Mean_Slope(j);
            cp{cpI,5} = morRes.CraterParams.Crater_Contour_Stats{i}.Crater_Median_Slope(j);
            cpI = cpI+1;
        end

        xlswrite(xlsFolFil,cp,sprintf('Crater_%d_Parameters',i))
    end
end